library(drake)
library(brms)
library(ggplot2)
library(cowplot)
library(dplyr)
library(colorspace)
library(rotl)
library(ape)
library(ggtree)
library(phytools)
library(ggstance)
library(bayesplot)
library(tidyverse)
library(reshape2)
library(ggridges)
library(colorspace)
library(gridExtra)

rstan::rstan_options(auto_write = TRUE)
options(mc.cores = parallel::detectCores())
